Allow Renderer_MultiMedias to use template string
novius/novius_renderers pull request #55
Opened 2017-08-16 08:34 UTC by TheoGil

In a crud where this renderer coexists with other fields, its appearance seems "buggy" due to the fact that is does not display a label.
This PR allows the Render_Multimedias to:
- By default use the same template as the other fields (label + field)
- Use the `template` option (same as other fields) so we can only display the field without the label or whatever is needed

![renderer_multimedias - before](https://user-images.githubusercontent.com/8545893/29354619-7fb73c62-826e-11e7-8005-4442548b2812.png)

2017-08-18 10:56 UTC, shaoshiva requested changes

2017-08-18 10:56 UTC, shaoshiva commented on classes/renderer/multimedias.php
> +        $template = $this->template ?: $this->fieldset()->form()->get_config('field_template', "<tr><th>{label} :</th> <td>{field}</td></tr>");
By setting `"<tr><th>{label} :</th> <td>{field}</td></tr>"` as default template you introduce a breaking change that will break existing renderers that are not in a `<table>` (like in the CRUD's accordion menu).

I would have set `{field}` as default template.

2017-08-21 14:54 UTC, alicecd commented on classes/renderer/multimedias.php
> +        $template = $this->template ?: $this->fieldset()->form()->get_config('field_template', "<tr><th>{label} :</th> <td>{field}</td></tr>");
You should add {required} after {label}

2017-08-28 14:50 UTC, SwithFr approved these changes

2017-08-29 09:59 UTC, Seb-C approved these changes

2017-08-29 10:02 UTC, alicecd approved these changes

2017-08-31 06:43 UTC, merged